//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.15 at 10:35:12 AM CET 
//


package fr.diginamic.jaxb.beans;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}population"/&gt;
 *         &lt;element ref="{}fecondite"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "population",
    "fecondite"
})
@XmlRootElement(name = "donneesDemographiques")
public class DonneesDemographiques {

    @XmlElement(required = true)
    protected Population population;
    @XmlElement(required = true)
    protected Fecondite fecondite;

    /**
     * Gets the value of the population property.
     * 
     * @return
     *     possible object is
     *     {@link Population }
     *     
     */
    public Population getPopulation() {
        return population;
    }

    /**
     * Sets the value of the population property.
     * 
     * @param value
     *     allowed object is
     *     {@link Population }
     *     
     */
    public void setPopulation(Population value) {
        this.population = value;
    }

    /**
     * Gets the value of the fecondite property.
     * 
     * @return
     *     possible object is
     *     {@link Fecondite }
     *     
     */
    public Fecondite getFecondite() {
        return fecondite;
    }

    /**
     * Sets the value of the fecondite property.
     * 
     * @param value
     *     allowed object is
     *     {@link Fecondite }
     *     
     */
    public void setFecondite(Fecondite value) {
        this.fecondite = value;
    }

}
