//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.15 at 10:35:12 AM CET 
//


package fr.diginamic.jaxb.beans;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="pays" maxOccurs="unbounded"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="nom" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element ref="{}dateDeReleve"/&gt;
 *                   &lt;element ref="{}donneesDemographiques"/&gt;
 *                   &lt;element ref="{}donneesEconomiques"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "pays"
})
@XmlRootElement(name = "paysListe")
public class PaysListe {

    @XmlElement(required = true)
    protected List<PaysListe.Pays> pays;

    /**
     * Gets the value of the pays property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the pays property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPays().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PaysListe.Pays }
     * 
     * 
     */
    public List<PaysListe.Pays> getPays() {
        if (pays == null) {
            pays = new ArrayList<PaysListe.Pays>();
        }
        return this.pays;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="nom" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element ref="{}dateDeReleve"/&gt;
     *         &lt;element ref="{}donneesDemographiques"/&gt;
     *         &lt;element ref="{}donneesEconomiques"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "nom",
        "dateDeReleve",
        "donneesDemographiques",
        "donneesEconomiques"
    })
    @XmlRootElement(name = "pays")
    public static class Pays {

        @XmlElement(required = true)
        protected String nom;
        @XmlElement(required = true)
        protected DateDeReleve dateDeReleve;
        @XmlElement(required = true)
        protected DonneesDemographiques donneesDemographiques;
        @XmlElement(required = true)
        protected DonneesEconomiques donneesEconomiques;
        

        /**
		 * @param nom
		 */
		public Pays(String nom) {
			super();
			this.nom = nom;
		}
		

		/**
		 * 
		 */
		public Pays() {
			super();
		}



		/**
         * Gets the value of the nom property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNom() {
            return nom;
        }

        /**
         * Sets the value of the nom property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNom(String value) {
            this.nom = value;
        }

        /**
         * Gets the value of the dateDeReleve property.
         * 
         * @return
         *     possible object is
         *     {@link DateDeReleve }
         *     
         */
        public DateDeReleve getDateDeReleve() {
            return dateDeReleve;
        }

        /**
         * Sets the value of the dateDeReleve property.
         * 
         * @param value
         *     allowed object is
         *     {@link DateDeReleve }
         *     
         */
        public void setDateDeReleve(DateDeReleve value) {
            this.dateDeReleve = value;
        }

        /**
         * Gets the value of the donneesDemographiques property.
         * 
         * @return
         *     possible object is
         *     {@link DonneesDemographiques }
         *     
         */
        public DonneesDemographiques getDonneesDemographiques() {
            return donneesDemographiques;
        }

        /**
         * Sets the value of the donneesDemographiques property.
         * 
         * @param value
         *     allowed object is
         *     {@link DonneesDemographiques }
         *     
         */
        public void setDonneesDemographiques(DonneesDemographiques value) {
            this.donneesDemographiques = value;
        }

        /**
         * Gets the value of the donneesEconomiques property.
         * 
         * @return
         *     possible object is
         *     {@link DonneesEconomiques }
         *     
         */
        public DonneesEconomiques getDonneesEconomiques() {
            return donneesEconomiques;
        }

        /**
         * Sets the value of the donneesEconomiques property.
         * 
         * @param value
         *     allowed object is
         *     {@link DonneesEconomiques }
         *     
         */
        public void setDonneesEconomiques(DonneesEconomiques value) {
            this.donneesEconomiques = value;
        }

    }

}
